{
  "hash": "b54240667d27ff42d2479d283b807400",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Blog 3: Extended Analysis and Equity Considerations\"\ndescription:  |\n  Description of datasets found.\nauthor: \"TEAMATE\"\ndate: \"2025-03-24\"\ndraft: FALSE\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nrm(list = ls())\n# hide warnings\noptions(warn = -1)\nsuppressPackageStartupMessages(library(ggplot2))\nsuppressPackageStartupMessages(library(tidyverse))\nsuppressPackageStartupMessages(library(dplyr))\nsuppressPackageStartupMessages(library(stargazer))\nsuppressPackageStartupMessages(library(readxl))\n\ndata <- readRDS(\"dataset/cleaned_data.rds\")\ncensus_data <- read_excel('dataset/NST-EST2024-POP.xlsx')\n```\n\n::: {.cell-output .cell-output-stderr}\n\n```\nNew names:\n• `` -> `...2`\n• `` -> `...3`\n• `` -> `...4`\n• `` -> `...5`\n• `` -> `...6`\n• `` -> `...7`\n```\n\n\n:::\n:::\n\n\n## Data Background and Context\nThe dataset originates from the landmark study *\"Systemic Discrimination Among Large U.S. Employers\"* (Kline, Rose, and Walters, 2022). \n\n- **Research Questions:** The study explores whether discrimination is endemic to particular firms, investigates firm-level heterogeneity in callback rates, and considers the potential impact of industry, geographic location, and other structural factors.\n\nThe census data was retrieved from the United States Census Bureau at this link: https://www.census.gov/data/tables/time-series/demo/popest/2020s-state-total.html\n\n## Extended Exploratory Analysis and Equity Considerations\n\nIn this update, I extend my analysis to delve deeper into the structure of the data and highlight important equity issues. By examining the distribution of submissions by state and comparing callback rates by race, the analysis aims to uncover potential systemic biases and inform further steps. \n\n## Check distribution of submissions by state\nThe following code creates a bar plot that orders states by the count of submissions. This visualization helps identify geographic patterns in the data, which may be related to regional hiring practices or other local factors.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata %>%\n  count(state) %>%\n  arrange(desc(n)) %>% \n  ggplot(aes(y = reorder(state, n), x = n)) +\n  geom_bar(stat = \"identity\", fill = \"skyblue\", color = \"black\") +\n  labs(\n    title = \"Distribution of States (Ordered by Count)\",\n    y = \"State\",\n    x = \"Count\"\n  )\n```\n\n::: {.cell-output-display}\n![](blog-3_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n\n## Check distribution of population by state\nThe following code organizes data from the U.S. Census Bureau and creates a bar plot that orders states by their population in 2024. This visualization highlights the distribution of population density across states, providing a clear comparison to the research data. By aligning the population data with the research findings, the plot demonstrates a correlation between states with higher populations and the number of samples collected in those states. \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncolnames(census_data)[1] <- \"states\"\n\ncensus_data <- census_data %>% \n  select(-2) %>% \n  slice(-(1:3))\n\ncolnames(census_data)[2:6] <- c(\"2020\", \"2021\", \"2022\", \"2023\", \"2024\")\n\ncensus_data <- census_data %>% filter(grepl(\"^\\\\.\", states))\n\ncensus_data <- census_data %>% \n  filter(states != \".Puerto Rico\") %>%\n  mutate(states = gsub(\"^\\\\.\", \"\", states)) \n\ncensus_data %>%\n  ggplot(aes(y = reorder(states, `2024`), x = `2024`)) +  # Use backticks for column names\n  geom_bar(stat = \"identity\", fill = \"skyblue\", color = \"black\") +\n  labs(\n    title = \"Population Distribution by State (2024)\",\n    y = \"State\",\n    x = \"Population\"\n  ) \n```\n\n::: {.cell-output-display}\n![](blog-3_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n\n\n# Check Black and White Difference to Any Callback\n(Note: `race`, and `cb` are the variables of interest)\n\nIn this section, I focus on evaluating the callback rates between Black and White applicants. The variable `cb` indicates whether an applicant received a callback (1 = Yes, 0 = No), and the regression analysis estimates the difference between the two groups using a logistic model. White applicants are set as the reference group.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndf <- data %>%\n  filter(race %in% c(\"Black\", \"White\")) %>%\n  mutate(race = factor(race, levels = c(\"White\", \"Black\")))\n\nmodel <- glm(cb ~ race, data = df, family = binomial(link = \"logit\"))\n\n\nstargazer(model, type = \"text\",\n          title = \"Logit: Difference in Any Callback by Race\",\n          dep.var.labels = \"Any Callback (1 = Yes, 0 = No)\",\n          covariate.labels = \"Race (Black)\",\n          digits = 3)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nLogit: Difference in Any Callback by Race\n================================================\n                       Dependent variable:      \n                  ------------------------------\n                  Any Callback (1 = Yes, 0 = No)\n------------------------------------------------\nRace (Black)                -0.112***           \n                             (0.016)            \n                                                \nConstant                    -1.096***           \n                             (0.011)            \n                                                \n------------------------------------------------\nObservations                  83,643            \nLog Likelihood             -46,101.830          \nAkaike Inf. Crit.           92,207.660          \n================================================\nNote:                *p<0.1; **p<0.05; ***p<0.01\n```\n\n\n:::\n:::\n\n\nThe logit regression shows that Black applicants have significantly lower odds of receiving a callback compared to White applicants, with a coefficient of -0.112 (p<0.01). The constant of -1.096 represents the baseline log-odds of receiving a callback for White applicants. The model, estimated on 83,643 observations, has a log-likelihood of -46,101.830. ",
    "supporting": [
      "blog-3_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}